functions

diff --git a/02-functions-sh b/02-functions-sh
--- a/02-functions-sh
+++ b/02-functions-sh
@@ -8,3 +8,27 @@ else
     echo "you are running with root access"
 
 fi
+
+VALIDATE() {
+    if [ $1 -eq 0 ]
+    then 
+        echo "installing $2 is ----success"
+    else
+        echo "installing $2 is ''''' failure"
+    exit 1
+
+    fi    
+}
+
+dnf list installed ngnix
+if [ $? -ne 0 ]
+
+then
+   echo "nignix is not installed"
+   dnf install nginx -y
+
+   VALIDATE $? "nginx"
+else
+
+   echo "nginx is already installed"
+fi
